# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a038c22c840fb91ee44601eaa6cf9ce1c677587337ec0c0132d6b113b1dc252e4862864d7ce67b08cb9cc7230f7103305625ddb30d64d8dec7e071391ed6a3c0

test:
  secret_key_base: 63e360ef5e2db116179ae892eef9caba69ae74133d20080974f84c28a60cda08d7c0674b89ee1889026eed4423513da34c1eb9e8cf68ac8fc7653e191cd1cbc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
